global_settings:
  model_dir: "/home/avpetrov/Synthetic-RNA-Maps/Code/singleic_ip_20cells_--"
  output_dir: "/home/avpetrov/Synthetic-RNA-Maps/Code/singleic_op_20cells_--"
  do_simulations: True
  do_post_processing: False
  modeltype: 'heaviside'

jobs:
  - name: "SingleIC"
    model_definition: "allowed_file.txt"
    model_initial_conditions: "rand_ICS.txt"
    simulation_time: 1
    num_cells: 1
    do_parallel: True
    integration_step_size: 0.001

post_processing:
  Dropouts:
    - dropout: False
      nCells: 1000
